### ISSUE TITLE
Need more explainations of maths behind approx_air_column_density_ratio_through_atmosphere()

### ISSUE THREAD

**Issue by Green92** [davidson16807/tectonics.glsl#1]
Hi,

Sorry for creating an issue here but I couldn't find any other way to contact you.
I read your [blog post](https://davidson16807.github.io/tectonics.js//2019/03/24/fast-atmospheric-scattering.html) about your improvement on atmospheric scattering rendering technic and was very interested in.

I'm trying to figure out how did you solve **∫exp(-(h(x))/H)dx** to get **−(H/h'(x))exp(−h(x)/H)** ?
I would be infinitely grateful if you bring the details of your process.

Sincerely,
Green

**Comment by davidson16807** [comment]
Sorry for the late reply, I don't check this repo often and I just noticed your comment.

It's not a proper integral solution, just an approximation to one. 

**(H/h'(x))exp(−h(x)/H)** is not the approximation we use, either.  **(H/h'(x))exp(−h(x)/H)** is what you get if you incorrectly applied integration by substitution. I say "incorrectly" because it introduces a division by 0 when x=0. It still produces a good approximation when x is far from 0, but when x is close to 0, the expression is way off.

So the trick then is to "nudge" the denominator by some value. Let's call this value "F". When x is far from 0, F falls to 0, so that the approximation is equivalent to the expression above, which is valid for that situation. When x is close to 0 though, the value for F is set to whatever it needs to be so that the entire approximation produces the correct value. So the approximation we actually use is **(H/(h'(x)+F))exp(−h(x)/H)**. We can further simplify this if x and h are measured relative to H, so that the integral to solve is **∫exp(-h(x))dx** and the solution is expressed as **exp(−h(x))/(h'(x)+F)**

In other words, rather than try to find an approximation for ∫exp(-h(x))dx, we're trying to find an approximation for F. We know what the "true" value for F is, since we assert that:

**exp(−h(x))/(h'(x)+F) = ∫exp(-h(x))dx**

solving for F algebraically gives:

**F = exp(−h(x)) / ∫exp(-h(x))dx  - h'(x)**

We can calculate what the "true" value is on a computer using numerical integration, then plot it for a range of values and find an approximation. It turns out this is easier than approximating the integral itself. The range of values we need to consider is much smaller. We also know from other people's work what the value of F ought to be for the case where x=0, so we just need to find an expression that transitions from this known value when x is small to 0 when x is large. 

Does that make sense?

**Comment by Green92** [comment]
Hi, better late than never ! Thanks for taking time to answere me.
Yes it make sense for your trick about approximation. But my question was precisely about **(H/h'(x))exp(−h(x)/H)**. Cause for me **∫exp(-(h(x))/H)dx** have no closed-form solution. I was stucked on in my comprehension of your article. So you mean this is an approximation of the closed form ?

**Comment by davidson16807** [comment]
Yes, sorry for the misunderstanding. You're correct that it has no closed form solution, **(H/h'(x))exp(−h(x)/H)** is only an approximation for the closed form, and it's a poor one at that, but it is useful as the basis for a better approximation.

**Comment by Green92** [comment]
Thank you for explanation !
